### ISSUE TITLE
Where can I find vrd_boxes36.h5?

### ISSUE THREAD

**Issue by ApolloZhu** [zhaoyucs/VSD#1]
Hi!

Thank you for making this interesting research study and making your code public! We are trying to reproduce the results as a part of our school project assignment, and I have looked around and was able to find most files needed. However, 

1. I'm unable to find any `vrd_boxes36.h5` to put in `sp3000`. Where can I download this file, or is there a way for me to produce this file myself from Spatialsense?
2. I assumed the `train/test/val.json` files that needs to be placed under the `spall` folder are the 3 JSON files in https://github.com/zhaoyucs/VSD/tree/master/dataset/VSDv2. Is this assumption correct?

Looking forward to your reply soon. You can also reach me at zhuzhiyu@cs.washington.edu or on WeChat, if that's more convenient for you.

**Comment by ApolloZhu** [comment]
To whoever that comes across this later, you can run `feature_extraction/sp_proposal.py` with all of VG + SP's images (yes, despite the sp3000 name) and it should work.

**Comment by zhangjingxian1998** [comment]
Hi, what is SP means. Is it a dataset name?
